version: '3.8'

services:
  zookeeper-order:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper-order
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka-Order:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka-order
    user: "0:0"
    depends_on:
      - zookeeper-order
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-order:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-order:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper-store:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper-store
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Must be 2181 internally
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22182:2181"  # External port can be anything

  kafka-store:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka-store
    user: "0:0"
    depends_on:
      - zookeeper-store
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-store:2181  # Internal port must be 2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-store:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1